'use client';
import { use, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import AppShell from '@/components/AppShell'; import AuthGate from '@/components/AuthGate'; import GlassCard from '@/components/GlassCard'; import RichHtml from '@/components/RichHtml'; import RichTextEditor from '@/components/RichTextEditor'; import { api } from '@/lib/api'; import type { Post } from '@/lib/types'; import { formatDate } from '@/lib/utils'; import { ArrowLeft,MessagesSquare,Reply,Send,X } from 'lucide-react';
type Data={activity:{activity_id:string;title:string;week_id:string;max_score:number};discussion:{discussion_id:string;prompt_html:string;min_posts?:number};posts:Post[]};
export default function DiscussionPage({params}:{params:Promise<{id:string}>}){const{id}=use(params);const[d,setD]=useState<Data|null>(null);const[content,setContent]=useState('');const[replyTo,setReplyTo]=useState<Post|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const load=()=>api<Data>('getDiscussion',{activity_id:id}).then(setD).catch(e=>setError(e.message));useEffect(()=>{load()},[id]);
 const byId=useMemo(()=>{const m:Record<string,Post>={};(d?.posts||[]).forEach(p=>m[p.post_id]=p);return m},[d?.posts]);
 const submit=async()=>{if(!d||!content.replace(/<[^>]+>/g,'').trim())return;setBusy(true);setError('');try{await api('createPost',{discussion_id:d.discussion.discussion_id,parent_post_id:replyTo?.post_id||'',content_html:content});setContent('');setReplyTo(null);await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <AuthGate><AppShell title="Diskusi"><Link href="/discussions" className="button soft compact"><ArrowLeft/>Kembali</Link>{error&&<div className="error-box">{error}</div>}{!d?<div className="screen-center small"><div className="spinner"/>Memuat diskusi...</div>:<div className="stack"><GlassCard><span className="eyebrow">{d.activity.week_id} • DISKUSI TERARAH</span><h2>{d.activity.title}</h2><RichHtml html={d.discussion.prompt_html}/><div className="row wrap gap"><span className="badge">Skala 0–100</span>{d.discussion.min_posts?<span className="badge">Minimal {d.discussion.min_posts} post</span>:null}</div></GlassCard><div className="discussion-stream">{d.posts.length?d.posts.map(p=>{const parent=p.parent_post_id?byId[p.parent_post_id]:null;return <GlassCard key={p.post_id} className={p.parent_post_id?'post-card reply-post':'post-card'}><div className="avatar">{(p.author?.name||'U').slice(0,1).toUpperCase()}</div><div className="grow"><div className="post-head"><div><strong>{p.author?.name||'Pengguna'}</strong><small>{p.author?.role?` • ${p.author.role}`:''}</small></div><small>{formatDate(p.created_at)}</small></div>{parent&&<div className="notice tiny">Membalas {parent.author?.name||'post sebelumnya'}</div>}<RichHtml html={p.content_html}/><button className="button soft compact" onClick={()=>setReplyTo(p)}><Reply/>Balas</button></div></GlassCard>}):<GlassCard><p className="muted">Belum ada respons. Jadilah yang pertama berdiskusi.</p></GlassCard>}</div><GlassCard><div className="row between wrap gap"><div><span className="eyebrow">TULIS RESPONS</span><h3>{replyTo?`Balas ${replyTo.author?.name||'post'}`:'Tambahkan post'}</h3></div>{replyTo&&<button className="icon-button" onClick={()=>setReplyTo(null)}><X/></button>}</div><RichTextEditor value={content} onChange={setContent} minHeight={150}/><div className="right-actions"><button className="button primary" disabled={busy||!content.replace(/<[^>]+>/g,'').trim()} onClick={submit}><Send/>{busy?'Mengirim...':'Kirim Respons'}</button></div></GlassCard></div>}</AppShell></AuthGate>}
