import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../${p}`,import.meta.url),'utf8');
const config=read('src/lib/courseConfig.ts');
const themes=read('src/lib/projectThemes.ts');
const setup=read('apps-script/Setup.gs');
const manifest=read('public/manifest.webmanifest');
const readme=read('README.md');
const checks=[]; const add=(name,ok)=>checks.push({name,ok});
add('2 SKS',config.includes('COURSE_SKS=2')&&config.includes('COURSE_CONTACT_MINUTES=100'));
add('16 pertemuan',Array.from({length:16},(_,i)=>config.includes(`base(${i+1},`)).every(Boolean)&&readme.includes('16 pertemuan'));
add('3 CPMK asli',config.includes('CPMK 1:')&&config.includes('CPMK 2:')&&config.includes('CPMK 3:'));
add('2 project definitions',themes.includes("code:'DESIGN_PROJECT'")&&themes.includes("code:'IMPLEMENTATION_PROJECT'"));
add('project bersifat individu',!themes.includes('group:true'));
add('project seed',setup.includes("project_code:'DESIGN_PROJECT'")&&setup.includes("project_code:'IMPLEMENTATION_PROJECT'"));
add('16 materi seed',setup.includes('var units=[')&&setup.includes("order_no:1")&&!setup.includes('pairs.forEach'));
add('satu unit per pertemuan',setup.includes('Satu pertemuan memuat satu unit materi inti'));
add('microcontroller sebagai interaktivitas',config.includes('Interaktivitas Berbasis Sensor dan Microcontroller')&&setup.includes('Physical Computing sebagai Interaktivitas'));
add('diskusi formatif seeded',setup.includes('DISC_CLT')&&setup.includes('DISC_INTERACTION')&&setup.includes('DISC_MICRO')&&setup.includes('DISC_TEST'));
add('PWA MPF',manifest.includes('MPF — Multimedia Pembelajaran Fisika')&&manifest.includes('standalone'));
add('weights 10/40/50',config.includes("weight:10")&&config.includes("weight:40")&&config.includes("weight:50"));
const failed=checks.filter(x=>!x.ok);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'} ${c.name}`);if(failed.length)process.exit(1);
